### PR TITLE
Update circle.yml

### PR DESCRIPTION
**Pull request by zuphilip**

### CODE REVIEW

**Comment by kba** [comment]
I you think this is better, just go ahead, no need for a PR IMHO.

**Comment by zuphilip** [comment]
Thanks :-) I am just playing with CircleCI here and needed something to trigger it...

**Comment by kba** [comment]
With CircleCI you can trigger manually from the project settings.

**Comment by kba** [comment]
And I didn't realize which repo I'm on, sorry for the noise.

**Comment by zuphilip** [comment]
No problem, we can clean the noise this later... ;-)

**Comment by zuphilip** [comment]
@kba Any idea why CircleCI is not jumping into this PR?

**Comment by kba** [comment]
Possibly something in https://circleci.com/gh/UB-Mannheim/ocropy/edit#advanced-settings. Forced it with the manual settings. https://circleci.com/gh/UB-Mannheim/ocropy/4

**Comment by zuphilip** [comment]
Okay, thank you very much. I don't understand where you have change anything, but it seems to work now :-)

**Pull request closed without merging**
